# Generated by Django 3.2.5 on 2021-07-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('host', models.CharField(max_length=35)),
                ('topic', models.TextField(help_text='Brief description of the topic described')),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
